const quotesData = [
  {
    text: 'Genius is one percent inspiration and ninety-nine percent perspiration.',
    author: 'Thomas Edison',
    comments: [
      { text: 'Excellent!', value: 10 },
      { text: 'Good!', value: 8 },
      { text: 'Not bad!', value: 5 },
      { text: 'Bad!', value: 3 },
    ],
    id: '1',
    sectionName: 'main',
  },
  {
    text: 'You can observe a lot just by watching.',
    author: 'Yogi Berra',
    comments: [
      { text: 'Excellent!', value: 9 },
      { text: 'Good!', value: 7 },
      { text: 'Good!', value: 6 },
      { text: 'Bad!', value: 3 },
    ],
    id: '2',
    sectionName: 'main',
  },
  {
    text: 'A house divided against itself cannot stand.',
    author: 'Abraham Lincoln',
    comments: [
      { text: 'Excellent!', value: 10 },
      { text: 'Good!', value: 8 },
      { text: 'Not bad!', value: 5 },
      { text: 'Bad!', value: 3 },
      { text: 'Excellent!', value: 10 },
      { text: 'Excellent!', value: 10 },
    ],
    id: '3',
    sectionName: 'main',
  },
  {
    text: 'Difficulties increase the nearer we get to the goal.',
    author: 'Johann Wolfgang von Goethe',
    comments: [
      { text: 'Excellent!', value: 9 },
      { text: 'Good!', value: 8 },
      { text: 'Not bad!', value: 5 },
      { text: 'Bad!', value: 3 },
      { text: 'Not bad!', value: 4 },
      { text: 'Excellent!', value: 8 },
    ],
    id: '4',
    sectionName: 'main',
  },
  {
    text: 'Fate is in your hands and no one elses',
    author: 'Byron Pulsifer',
    comments: [
      { text: 'Not bad!', value: 3 },
      { text: 'Good!', value: 8 },
      { text: 'Excellent!', value: 10 },
      { text: 'Bad!', value: 2 },
      { text: 'Not bad!', value: 4 },
      { text: 'Excellent!', value: 8 },
    ],
    id: '5',
    sectionName: 'main',
  },
  {
    text: 'Be the chief but never the lord.',
    author: 'Lao Tzu',
    comments: [
      { text: 'Excellent!', value: 10 },
      { text: 'Bad!', value: 2 },
      { text: 'Good!', value: 9 },
      { text: 'Not bad!', value: 5 },
      { text: 'Bad!', value: 3 },
    ],
    id: '6',
    sectionName: 'main',
  },
  {
    text: 'Nothing happens unless first we dream.',
    author: 'Carl Sandburg',
    comments: [
      { text: 'Excellent!', value: 10 },
      { text: 'Good!', value: 8 },
      { text: 'Not bad!', value: 5 },
      { text: 'Bad!', value: 3 },
      { text: 'Good!', value: 8 },
      { text: 'Not bad!', value: 6 },
      { text: 'Not bad!', value: 4 },
    ],
    id: '7',
    sectionName: 'main',
  },
  {
    text: 'Well begun is half done.',
    author: 'Aristotle',
    comments: [
      { text: 'Excellent!', value: 7 },
      { text: 'Good!', value: 6 },
      { text: 'Not bad!', value: 5 },
      { text: 'Bad!', value: 2 },
      { text: 'Not bad!', value: 4 },
      { text: 'Excellent!', value: 8 },
    ],
    id: '8',
    sectionName: 'main',
  },
  {
    text: 'Life is a learning experience, only if you learn.',
    author: 'Yogi Berra',
    comments: [
      { text: 'Not bad!', value: 4 },
      { text: 'Excellent!', value: 9 },
      { text: 'Good!', value: 8 },
      { text: 'Not bad!', value: 4 },
      { text: 'Bad!', value: 3 },
      { text: 'Not bad!', value: 6 },
    ],
    id: '9',
    sectionName: 'main',
  },
  {
    text: 'Self-complacency is fatal to progress.',
    author: 'Margaret Sangster',
    comments: [
      { text: 'Excellent!', value: 10 },
      { text: 'Good!', value: 8 },
      { text: 'Not bad!', value: 5 },
      { text: 'Excellent!', value: 10 },
      { text: 'Bad!', value: 3 },
      { text: 'Excellent!', value: 10 },
      { text: 'Excellent!', value: 10 },
    ],
    id: '10',
    sectionName: 'main',
  },
];

export default quotesData;
