export const quotes = [
  {
    text: 'Genius is one percent inspiration and ninety-nine percent perspiration.',
    author: 'Thomas Edison',
    comments: [
      { id: '1', text: 'this author is a very creative student.', value: 10 },
      {
        id: '2',
        text: 'this author is doing well for his abilities.',
        value: 8,
      },
      {
        id: '3',
        text: 'I seem to learn something new about this author every day.',
        value: 5,
      },
      {
        id: '4',
        text: 'I think this author brings a unique energy to my class.',
        value: 3,
      },
    ],
    id: '1',
    sectionName: 'main',
  },
  {
    text: 'You can observe a lot just by watching.',
    author: 'Yogi Berra',
    comments: [
      {
        id: '1',
        text: 'I can see that this author has many strengths as a student.',
        value: 9,
      },
      {
        id: '2',
        text: 'I see a lot of potential in this author as an English student.',
        value: 7,
      },
      {
        id: '3',
        text: 'this author shows a lot of promise as an English student.',
        value: 6,
      },
      {
        id: '4',
        text: 'Its always interesting to have this author in my class.',
        value: 3,
      },
    ],
    id: '2',
    sectionName: 'main',
  },
  {
    text: 'A house divided against itself cannot stand.',
    author: 'Abraham Lincoln',
    comments: [
      {
        id: '1',
        text: 'As a teacher, I like to focus a lot on this author.',
        value: 10,
      },
      {
        id: '2',
        text: 'I learn something new about this author every day.',
        value: 8,
      },
      {
        id: '3',
        text: 'I think this author is a very consistent student.',
        value: 5,
      },
      {
        id: '4',
        text: 'this author shows a lot of creativity in my class.',
        value: 3,
      },
      {
        id: '5',
        text: 'I enjoy when he gives his answers in the classroom.',
        value: 10,
      },
      {
        id: '6',
        text: 'He often likes to participate in class or help his classmates with the work when he knows the answer.',
        value: 10,
      },
    ],
    id: '3',
    sectionName: 'main',
  },
  {
    text: 'Difficulties increase the nearer we get to the goal.',
    author: 'Johann Wolfgang von Goethe',
    comments: [
      {
        id: '1',
        text: 'When he is confident about the answer, he loves to participate in class.',
        value: 9,
      },
      {
        id: '2',
        text: 'He likes participating in class activities.',
        value: 8,
      },
      {
        id: '3',
        text: 'He gets very excited when he sees an opportunity to participate in class and show off his English skills.',
        value: 5,
      },
      { id: '4', text: 'I love when he participates in class.', value: 3 },
      {
        id: '5',
        text: 'I always love the effort he puts forth whenever he participates in the classroom.',
        value: 4,
      },
      {
        id: '6',
        text: 'He loves to participate when he knows the answer.',
        value: 8,
      },
    ],
    id: '4',
    sectionName: 'main',
  },
  {
    text: 'Fate is in your hands and no one elses',
    author: 'Byron Pulsifer',
    comments: [
      {
        id: '1',
        text: 'He loves when he can use new words he learned in class.',
        value: 3,
      },
      {
        id: '2',
        text: 'He has demonstrated that he is able to learn new vocabulary quite quickly when he wants to.',
        value: 8,
      },
      {
        id: '3',
        text: 'I see him use new words he has learned in his work frequently.',
        value: 10,
      },
      {
        id: '4',
        text: 'He has learned a lot of new vocabulary through the class readings and our lessons!',
        value: 2,
      },
      {
        id: '5',
        text: 'He is being challenged to learn new words every day during my lessons.',
        value: 4,
      },
      {
        id: '6',
        text: 'He seems to be acquiring a natural speaking grammar from listening English-speaking in class, which is great.',
        value: 8,
      },
    ],
    id: '5',
    sectionName: 'main',
  },
  {
    text: 'Be the chief but never the lord.',
    author: 'Lao Tzu',
    comments: [
      { id: '1', text: 'Excellent!', value: 10 },
      { id: '2', text: 'Bad!', value: 2 },
      { id: '3', text: 'Good!', value: 9 },
      { id: '4', text: 'Not bad!', value: 5 },
      { id: '5', text: 'Bad!', value: 3 },
    ],
    id: '6',
    sectionName: 'main',
  },
  {
    text: 'Nothing happens unless first we dream.',
    author: 'Carl Sandburg',
    comments: [
      { id: '1', text: 'Excellent!', value: 10 },
      { id: '2', text: 'Good!', value: 8 },
      { id: '3', text: 'Not bad!', value: 5 },
      { id: '4', text: 'Bad!', value: 3 },
      { id: '5', text: 'Good!', value: 8 },
      { id: '6', text: 'Not bad!', value: 6 },
      { id: '7', text: 'Not bad!', value: 4 },
    ],
    id: '7',
    sectionName: 'main',
  },
  {
    text: 'Well begun is half done.',
    author: 'Aristotle',
    comments: [
      { id: '1', text: 'Excellent!', value: 7 },
      { id: '2', text: 'Good!', value: 6 },
      { id: '3', text: 'Not bad!', value: 5 },
      { id: '4', text: 'Bad!', value: 2 },
      { id: '5', text: 'Not bad!', value: 4 },
      { id: '6', text: 'Excellent!', value: 8 },
    ],
    id: '8',
    sectionName: 'main',
  },
  {
    text: 'Life is a learning experience, only if you learn.',
    author: 'Yogi Berra',
    comments: [
      { id: '1', text: 'Not bad!', value: 4 },
      { id: '2', text: 'Excellent!', value: 9 },
      { id: '3', text: 'Good!', value: 8 },
      { id: '4', text: 'Not bad!', value: 4 },
      { id: '5', text: 'Bad!', value: 3 },
      { id: '6', text: 'Not bad!', value: 6 },
    ],
    id: '9',
    sectionName: 'main',
  },
  {
    text: 'Self-complacency is fatal to progress.',
    author: 'Margaret Sangster',
    comments: [
      { id: '1', text: 'Excellent!', value: 10 },
      { id: '2', text: 'Good!', value: 8 },
      { id: '3', text: 'Not bad!', value: 5 },
      { id: '4', text: 'Excellent!', value: 10 },
      { id: '5', text: 'Bad!', value: 3 },
      { id: '6', text: 'Excellent!', value: 10 },
      { id: '7', text: 'Excellent!', value: 10 },
    ],
    id: '10',
    sectionName: 'main',
  },
];
